import { PageHeader } from "@/components/ui/PageHeader";
import { Section } from "@/components/ui/Section";

export default function SafetyCompilerPage() {
  return <div><PageHeader eyebrow="Compiled safety artifacts" title="Safety Compiler" description="Translate local Watchtower and Preflight decisions into portable, reviewable safety controls." /><div className="grid gap-5 lg:grid-cols-2"><Section title="Generated by Watchtower"><p className="text-sm leading-6 text-slate-600">Each Watchtower run generates `.agent-safety.yml`, a commit gate, a Safety Compiler output, a local policy lock, and human- and machine-readable reports.</p></Section><Section title="Local and static"><p className="text-sm leading-6 text-slate-600">The compiler summarizes static local analysis. It does not execute project code, agent tools, hooks, or external services.</p></Section></div></div>;
}
